"""empty message

Revision ID: 474b669a8c53
Revises: a4df3e24e393
Create Date: 2023-01-27 03:54:40.998203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474b669a8c53'
down_revision = 'a4df3e24e393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sensor', sa.String(length=120), nullable=False),
    sa.Column('temp', sa.String(length=120), nullable=False),
    sa.Column('hum', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hum')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('l_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=480), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('url_image', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('url_image')
        batch_op.drop_column('rol')
        batch_op.drop_column('salt')
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('l_name')
        batch_op.drop_column('f_name')

    op.drop_table('registers')
    # ### end Alembic commands ###
